;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Action.Attacking",DevComment="")
+GameplayTagList=(Tag="Action.Reloading",DevComment="If actor is reloading")
+GameplayTagList=(Tag="Action.Sprinting",DevComment="")
+GameplayTagList=(Tag="Action.SwapItems",DevComment="For swapping items")
+GameplayTagList=(Tag="Keycard.Blue",DevComment="")
+GameplayTagList=(Tag="Keycard.Red",DevComment="")
+GameplayTagList=(Tag="Keycard.Yellow",DevComment="")
+GameplayTagList=(Tag="LevelExit",DevComment="For triggering level exit on obj complete")
+GameplayTagList=(Tag="Status.Burning",DevComment="")
+GameplayTagList=(Tag="Status.Parrying",DevComment="")
+GameplayTagList=(Tag="Status.Stunned",DevComment="")
+GameplayTagList=(Tag="Status.Thorns",DevComment="")

